#!/bin/bash
CACHE_FILE_INSTALLED=/tmp/eix-installed
CACHE_FILE_ALL=/tmp/eix-all

function updateGetAllCache {
  # shellcheck disable=SC2016
  equery list -p -F '$cp' "*" | uniq | tee >(sort > $CACHE_FILE_ALL)
}

function updateGetInstalledCache {
  # shellcheck disable=SC2016
  equery list -F '$cp' "*" | uniq | tee >(sort > $CACHE_FILE_INSTALLED)
}

function getPackages {
  cat "$CACHE_FILE"
}

refresh=0
CACHE_FILE=$CACHE_FILE_INSTALLED
updateGetCache=updateGetInstalledCache
EIX="eix -I"
while getopts "fia" opt; do
  case ${opt} in
    f )
      refresh=1
      ;;
    i)
      CACHE_FILE=$CACHE_FILE_INSTALLED
      updateGetCache=updateGetInstalledCache
      EIX="eix -I"
      ;;
    a)
      CACHE_FILE=$CACHE_FILE_ALL
      updateGetCache=updateGetAllCache
      EIX="eix"
      ;;
    * )
      ;;
  esac
done
shift $((OPTIND -1))

if [ ! -f $CACHE_FILE ]; then
  refresh=1
fi

packagesCall=getPackages
if [ $refresh -eq 1 ]; then
  packagesCall=$updateGetCache
fi

if [ ${#} -gt 0 ]; then
  package=$($packagesCall | fzf-tmux +s -1 -q "${1}")
else
  package=$($packagesCall | fzf-tmux +s)
fi

if [ -n "${package}" ]; then
  $EIX -e "${package}"
fi
